export const USER_AUTH = "USER_AUTH"; 
export const USER_LOGGEDIN = "USER_LOGGEDIN";

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_NUMBERS_BASKET = 'GET_NUMBERS_BASKET';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';


